using CommandLine;
using EventILWeaver.Console.AddEvents;

namespace EventILWeaver.Console.ListExistingAutoGeneratedEvents
{
    [Verb("list-existing", HelpText = "Shows existing auto generated events")]
    public class ListExistingAutoGeneratedEventsOptions
    {
        [Option('t', "target-dll-path", Required = true, HelpText = AddEventsOptions.TargetDllPathHelpText)]
        public string TargetDllPath { get; set; }

    }
}